### ISSUE TITLE
Fix: Avoid "deprecated" at old repository

### ISSUE THREAD

**Issue by franz-josef-kaiser** [quickube/piper#17] opened 2024-02-09 19:27 UTC
I went the Argo Projects README and saw a link to your projects repository. After following the link, I found a "deprecated" notice and filed [an issue](https://github.com/argoproj/argo-workflows/issues/12613) at the Argo Project to have the link to your repo removed. Gladly @agilgur5 spotted my mistake and correctly hinted, that you might not want to name it "deprecated", but *MOVED TO NEW LOCATION*  instead. I guess most people will read it like me: Your project is unmaintained and gone. Hope you can fix that as your project is something worth keeping around.

**Comment by GoshaDo** [comment] 2024-05-12 13:07
@franz-josef-kaiser Hi thanks for the feedback, link in ArgoWorkflows repo fixed thanks to @agilgur5 . Closing the issue.

**Closed by GoshaDo** 2024-05-12 13:07 UTC

**Comment by agilgur5** [comment] 2024-05-12 14:12
https://github.com/Rookout/piper/pull/126 hasn't been merged though, that's what the issue is about, not Argo's link. There are likely other old links to the old repo from various places.

I don't think this should be closed until the old repo's README is fixed, since that's what the issue is about.

**Comment by agilgur5** [comment] 2024-05-15 15:36
> [Rookout/piper#126](https://github.com/Rookout/piper/pull/126) hasn't been merged though

It's merged now 🚀
